### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by lorglas**
New YAB_Version. Incl. Changes Changes_to_1.7.7.yab
Multimedia Sound added. See Changes_to_1.7.8.yab.

### CODE REVIEW

**Comment by lorglas** [comment]
New YAB Version 1.7.8.
New Commands Added/ Old new Implemeted

**Comment by bbjimmy** [comment]
What has changed?  What is new and what problems have been coerected?

**Comment by lorglas** [comment]
New commands:
Mediasound Play 
Mediasound stop
Old reimplemented
Sound Play
Sound stop
Sound pause (There is a noise to hear. It is a Bug in haiku. I Post it bugtracker.)
Commands correctet:
Texturl redraws Text on mouseover again and again. Problem is solved.
Some grapchic issue in. Same height and so on. 
See in directory changes, app changes to yab 1.7.8.
Before you use this app go in the Terminal and change into the directory, otherwise the treebox isn't Working.
In the Next yab-Version we will correct the complete package in separate once.

**Comment by lorglas** [comment]
I must changed the yab commands. I Think i forgot the new commands

**Comment by bbjimmy** [comment]
I downloaded a copy of your repo. The new source seems to be one directory up from where it needs to be thus having two copies. one in the root and one in the src sub-dir. I compiled from the src sub-dir and had no trouble, but no mediasound. the src in the root has the mediasound commands but wioll not compile... 


runtime_loader: /boot/home/Desktop/YAB-1-YAB_1.7.8/yab: Could not resolve symbol 'mediasoundstop'


I think this pr must be closed and not merged as it would end up messing up my repo with duplicate srce files as well. Obviously you have a copy of the source that does compile. There has to be a way to get me the source in a state that I can compile as well so we can move forward.

**Pull request closed without merging**
